### PR TITLE
allow to set the entity->id as path transformer

### PR DESCRIPTION
**Pull request by impronta48**
Hi,
I've made a little modification in the entity transformer to allow integers to be parsed.
In particular, I needed the path to be
articles/3/attachments
(where 3 is the $article->id)
and the provided transformer did not allow this.

Can you kindly merge?
Thanks
Massimo

### CODE REVIEW

**Comment by josbeir** [comment]
Hi, looks like a nice adition!

Could you just make sure that the code coverage keeps at 100% (write a test) and there are no CS issues? (see https://travis-ci.org/github/josbeir/cakephp-filesystem/jobs/672247684)

**Comment by impronta48** [comment]
Hi,

fine for me, I'm not an expert in testing, but I'll try my best.

I'll make another pull request asap.

Regards

Massimo

Il 08/04/2020 14:12, Jasper Smet ha scritto:

**Comment by impronta48** [comment]
Hi,
sorry for the delay: I've added one test and fixed the cs.
I see above some threatening messages, what shall I do?

Do you think you can pull my request, now? Let me know if I should do something more.

Thanks a lot,
Massimo

**Comment by josbeir** [comment]
Thanks! 

The codecov check is failing because the codeblock you created (is_integer..) is not tested by the test case, this should be resolved as code coverage should be 100% 

See https://codecov.io/gh/josbeir/cakephp-filesystem/commit/312cdbbe444a0866cded17e21b80ab1cab676c7f#D1-49

**Comment by impronta48** [comment]
Hi,
I had added this test in FilesystemTest.php, which passes (you see that I'm using an integer as an id).
This is actually my case: the id is an integer, and I want a folder called /documents/1/...

Can you help me understand what is wrong?
Sorry, as you have understood, I'm not familiar with codecov.
Regards,
Massimo


    /**
     * Test custom formatter patterns with integer
     *
     * @return void
     */
    public function testEntityFormatterCustomPatternWithInt()
    {
        $entity = new Entity([
            'id' => 1,
            'name' => 'hello world this is cool',
        ], [ 'source' => 'articles' ]);

        $path = $this->manager
            ->setFormatter('Entity')
            ->newFormatter('cool-image.png', [
                'data' => $entity,
                'pattern' => '{entity-source}/{id}/{name}.{file-ext}',
            ])
            ->getPath();

        $this->assertSame('articles/1/hello_world_this_is_cool.png', $path);
    }

**Pull request closed without merging**
